### ISSUE TITLE
Cannot install packages

### ISSUE THREAD

**Issue by grumpycatsaysno** [Sitefinity/Telerik.Sitefinity.Samples.Quantum#22]
There are private repos in the nuget.config:

<packageSources>
    <add key="Telerik Private Repo" value="\\telerik.com\distributions\Nuget" />
    <add key="Sitefinity Private Repo" value="\\telerik.com\distributions\OfficialReleases\Sitefinity\nuget" />
    <add key="Sitefinity Public Repo" value="http://nuget.sitefinity.com/nuget/"/>
    <add key="NuGet official package source" value="https://nuget.org/api/v2/" />
  </packageSources>

 that contain packages such as: Progress.Sitefinity.AdminApp 

This results in being unable to install all packages for the solution and inability to open backend Content views for News, Blogs, etc.

**Comment by orlindraganov** [comment]
We'll have a look at it.

**Comment by orlindraganov** [comment]
Thank you for bringing this to our attention, the issue should be resolved.  #23

**Comment by fitz-ez** [comment]
This is once again an issue. The private repos were added back into the config in commit [3c97ac3fbdf6b054991ed180adae4e9a84438ef7](https://github.com/Sitefinity/Telerik.Sitefinity.Samples.Quantum/commit/3c97ac3fbdf6b054991ed180adae4e9a84438ef7)

**Comment by gg3orgiev** [comment]
We have removed the repositories. Thanks for the report.
