### ISSUE TITLE
WebAgency Addon doesn't exist

### ISSUE THREAD

**Issue by mekinney** [Sitefinity/Telerik.Sitefinity.Samples.Quantum#25]
> To import the sample content for the web agency add-on, log into the backend, navigate to Administration->Add-ons, click on the WebAgency add-on and activate it.

The WebAgency add-on doesn't exist on the Add-ons screen.  There are actually no add-ons listed.  The rest of the quantum website is present.  Not sure if this is a database or project related issue.

**Comment by gg3orgiev** [comment]
Hi mekinney, 

Thank you for bringing the issue to our attention. We have updated the documentation in the README to reflect the latest changes in the Quantum sample. Unfortunately we no longer provide an AddOn to import sample content. The content from the AddOn is now present by default when you launch the Quantum sample project.

If you wish to check the AddOn functionality of the Sitefinity CMS you can follow the documentation at https://www.progress.com/documentation/sitefinity-cms/sitefinity-cms-add-ons and import one of the [sample AddOns](https://www.progress.com/documentation/sitefinity-cms/sample-add-ons) to your existing instance of the Quantum sample.

The Quantum sample project is also used in our Sitefinity online sandboxes. You can sign up for one and check out all the available project functionality here: https://www.progress.com/sitefinity-cms/try-now/sandbox

Regards,
Georgi
