### ISSUE TITLE
Page Templates don't match Readme

### ISSUE THREAD

**Issue by mekinney** [Sitefinity/Telerik.Sitefinity.Samples.Quantum#26]
There are two "default" templates and a quantum1 template that isn't explain.  It looks like possibly a database was uploaded that had someone's test changes still in it.

**Comment by gg3orgiev** [comment]
Hi mekinney, 

The two "default" template are for different resource packages - Bootstrap3 and Bootstrap4. 
The quantum1 template is shared and used by the Quantum UK and Quantum SA sites.

Regards,
Georgi
