### ISSUE TITLE
Wrong nuget reference 

### ISSUE THREAD

**Issue by DMXS33** [Sitefinity/Telerik.Sitefinity.Samples.Quantum#28]
The current version 12.2.7200 has a nuget reference to Progress.Sitefinity.AdminApp version 12.2.40190  that doesn't exist on your nuget repository https://nuget.sitefinity.com/#/package/Progress.Sitefinity.AdminApp

**Comment by ivandimitrov** [comment]
The issue is not presented on the latest version in the master.
