### ISSUE TITLE
Remote database with error 'Incorrect credentials' on connect 

### ISSUE THREAD

**Issue by hoanq1811** [Sitefinity/Telerik.Sitefinity.Samples.Quantum#49]
Hi,
I have a problem related to a remote database connection from a local source
I have built it successfully but when I go to ~/Sitefinity to log in it is giving the error: Incorrect credentials even though the account is correct because I can log in to it on the domain name on the server. I don't understand what's wrong with it.

![image](https://user-images.githubusercontent.com/84486392/118910280-68b1c300-b94e-11eb-92e1-8b4af43ffb8d.png)
![image](https://user-images.githubusercontent.com/84486392/118910533-d0680e00-b94e-11eb-8513-38b1ebc2f9ff.png)

DB connection: 
connectionString="data source=<IP remote>;UID=<uid>;PWD=<pw>;initial catalog=<db name>" name="Sitefinity"

Thanks

**Comment by gg3orgiev** [comment]
Hi @hoanq1811,

I have tested the described setup on my end and unfortunately I couldn't reproduce the issue.

Could you turn on the authentication logging as described in this article: [https://www.progress.com/documentation/sitefinity-cms/turn-on-authentication-logging](https://www.progress.com/documentation/sitefinity-cms/turn-on-authentication-logging) . After that could you please archive the whole folder from _App_Data\Sitefinity\Logs_ and attach them so I can review them?

Can you confirm if you are able to login with the default admin user (u: admin@test.test, p: admin@2) from the localhost domain?

Regards,
Georgi
