### ISSUE TITLE
Can't run nuget restore on Quantum solution

### ISSUE THREAD

**Issue by strwase** [Sitefinity/Telerik.Sitefinity.Samples.Quantum#81]
Hi, when I download the solution and try to build it, I get the following error

Error		NuGet Package restore failed for project SitefinityWebApp: Unable to find version '14.2.7900.623' of package 'Progress.Sitefinity.AdminApp'.

that particular version of this package seems to no longer exist on your nuget feed:
![image](https://user-images.githubusercontent.com/10077785/178731263-1526dab3-d4be-4f87-ba09-3303b22f01bc.png)

Updating the package to the next available version also doesn't work.

Any recommendations?

Thank you

**Comment by gg3orgiev** [comment]
Hi strwase,

I have updated the package to the appropriate version, could you please try again and let me know if the issue persists ?

Regards,
Georgi
